version: '3'

services:
  backend:
    build: ./simple-django-project-with-db
    command:
      - sh
      - -c
      - |
        python3 manage.py collectstatic --noinput
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
        gunicorn simple_django_project_with_db.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/app/staticfiles
    ports:
      - "8005:8005"

volumes:
  static_volume: