version: '3'

services:
  backend:
#    build: ../../demo-django-project
    image: "ghcr.io/alexgorji/demo-django-project:0.1"
    container_name: demo-backend
    command:
      - sh
      - -c
      - |
        python3 manage.py collectstatic --noinput
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
        gunicorn demo_django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/app/staticfiles
      - media_volume:/var/www/app/protected
      - backup_volume:/var/www/app/backup-data
    env_file:
      - ../.env.dev
    expose:
      - 8000
    depends_on:
      - db
  db:
    build: ../postgres
    container_name: demo-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - backup_volume:/var/usr/backup-data
    environment:
      - POSTGRES_USER=ansibleadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simple_django_tasks

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/app/staticfiles
      - media_volume:/var/www/app/protected
    ports:
      - "8007:8007"
    depends_on:
      - backend
  git-backup:
    build: ./git-backup
    container_name: demo-git-backup
    volumes:
      - ../sshkey:/var/usr/git/sshkey
      - backup_volume:/var/usr/git/backup-data

    environment:
      - SSHKEY_PATH=/var/usr/git/sshkey
      - GITHUB_USER_EMAIL=alexgorji@hotmail.com
      - GITHUB_USER_NAME=alexgorji-django-server
      - BACKUP_REPOSITORY=git@github.com:alexgorji/demo-docker-backup.git
      - BACKUP_DATA_PATH=/var/usr/git/backup-data
      - BACKUP_REPOSITORY_NAME=demo-docker-backup
  backup:
    build: ./backup
    privileged: true
    volumes:
      - backup_volume:/var/usr/backup-data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CRON_MINUTE=60
    depends_on:
      - backend
      - db
      - git-backup

volumes:
  static_volume:
  media_volume:
  postgres_data:
  backup_volume:

