version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./simple-html-2:/var/www/simple-html-2
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8002:8002"