services:
  nginx:
    image: nginx:latest
    volumes:
      - ./simple-html-1:/var/www/simple-html-1
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8001:8001"