version: '3'

services:
  backend:
    build: ../../demo-django-project
    command:
      - sh
      - -c
      - |
        python3 manage.py collectstatic --noinput
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
        gunicorn demo_django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/app/staticfiles
      - media_volume:/var/www/app/protected
      - backup_volume:/var/www/app/backup
    env_file:
      - ./.env.dev
    expose:
      - 8000
    depends_on:
      - db
  db:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - backup_volume:/var/usr/backup
    environment:
      - POSTGRES_USER=ansibleadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simple_django_tasks

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/app/staticfiles
      - media_volume:/var/www/app/protected
    ports:
      - "8007:8007"
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
  postgres_data:
  backup_volume:

